sonar.projectKey=flash_card
sonar.projectName=flash_card
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.login=sqa_14b2c45ffc8103ffa50434577b717c6a89a2526e