package com.flash_card.model.entity;

import static org.junit.jupiter.api.Assertions.*;
import com.flash_card.model.entity.Quiz;
import com.flash_card.model.entity.User;
import com.flash_card.model.entity.FlashcardSet;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.LocalDateTime;

import static org.junit.jupiter.api.Assertions.*;

public class QuizTest {

    private User user;
    private FlashcardSet flashcardSet;
    private Quiz quiz;

    @BeforeEach
    public void setUp() {
        // Create real instances of User and FlashcardSet
        user = new User("789", "Jo", "Hands", "jo@gmail.com", "123456");
        flashcardSet = new FlashcardSet("Java Basics", "A set for Java beginners", "Programming", user);
        quiz = new Quiz(user, flashcardSet, LocalDateTime.now(), LocalDateTime.now().plusMinutes(10), 5, 2);
    }

    @Test
    public void testQuizConstructor() {
        assertNotNull(quiz);
        assertEquals(user, quiz.getUser());
        assertEquals(flashcardSet, quiz.getFlashcardSet());
        assertNotNull(quiz.getStartTime());
        assertNotNull(quiz.getEndTime());
        assertEquals(5, quiz.getCorrectTimes());
        assertEquals(2, quiz.getWrongTimes());
    }

    @Test
    public void testQuizGetters() {
        assertEquals(user, quiz.getUser());
        assertEquals(flashcardSet, quiz.getFlashcardSet());
        assertNotNull(quiz.getStartTime());
        assertNotNull(quiz.getEndTime());
        assertEquals(5, quiz.getCorrectTimes());
        assertEquals(2, quiz.getWrongTimes());
    }

    @Test
    public void testQuizSetters() {
        User newUser = new User("123", "Mock", "User", "mock.user@gmail.com", "2f7b9c4e-5d12-4a8f-bf6e-9c3d2a6b8e5f");
        FlashcardSet newSet = new FlashcardSet("Advanced Java", "A set for advanced Java learners", "Programming", newUser);

        quiz.setUser(newUser);
        quiz.setFlashcardSet(newSet);
        quiz.setStartTime(LocalDateTime.now().plusMinutes(5));
        quiz.setEndTime(LocalDateTime.now().plusMinutes(15));
        quiz.setCorrectTimes(10);
        quiz.setWrongTimes(1);

        assertEquals(newUser, quiz.getUser());
        assertEquals(newSet, quiz.getFlashcardSet());
        assertNotNull(quiz.getStartTime());
        assertNotNull(quiz.getEndTime());
        assertEquals(10, quiz.getCorrectTimes());
        assertEquals(1, quiz.getWrongTimes());
    }

    @Test
    public void testEmptyConstructor() {
        Quiz emptyQuiz = new Quiz();
        assertNotNull(emptyQuiz);
    }

    @Test
    public void testSettersAndGettersTogether() {
        quiz.setCorrectTimes(10);
        quiz.setWrongTimes(3);
        quiz.setStartTime(LocalDateTime.now().minusMinutes(5));
        quiz.setEndTime(LocalDateTime.now().plusMinutes(5));

        assertEquals(10, quiz.getCorrectTimes());
        assertEquals(3, quiz.getWrongTimes());
        assertNotNull(quiz.getStartTime());
        assertNotNull(quiz.getEndTime());
    }

    @Test
    public void testQuizIdShouldBeAutoGenerated() {
        // Assume quizId is auto-generated when persisting entity (this would be tested in an integration test)
        assertEquals(0, quiz.getQuizId()); // quizId would be auto-generated during persistence
    }
}